In [12]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('~/Downloads/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
peter_data=pd.DataFrame({'Age':[24],'Name':['Peter'],'Survived':['Y']})
pd.concat([df,peter_data], ignore_index=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,888.0,1,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,B42,S
888,889.0,0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,2.0,W./C. 6607,23.4500,NaN,S
889,890.0,1,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,C148,C
890,891.0,0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,NaN,Q
891,NaN,Y,NaN,Peter,NaN,24.0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df=df.drop(df.index[-1],axis=0)
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C

In [11]:
df=df.sort_values(by='Age', ascending=False)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [16]:
sno=[i+1 for i in range(50)]
marks=np.random.randint(50,size=50)
marks_df=pd.DataFrame({'Sno':sno,'Marks':marks})
marks_df.head()

   Sno  Marks
0    1     44
1    2     14
2    3     47
3    4     31
4    5     45

In [17]:
sno=[i+1 for i in range(50)]
age=np.random.randint(50,size=50)
age_df=pd.DataFrame({'Sno':sno,'Age':age})
age_df.head()

   Sno  Age
0    1   23
1    2    3
2    3   48
3    4    2
4    5   34

In [25]:
#merging two dataframes
cross_df=pd.merge(marks_df,age_df,how='cross')
display(cross_df.head())
display(cross_df.tail())

   Sno_x  Marks  Sno_y  Age
0      1     44      1   23
1      1     44      2    3
2      1     44      3   48
3      1     44      4    2
4      1     44      5   34

      Sno_x  Marks  Sno_y  Age
2495     50     15     46   47
2496     50     15     47   45
2497     50     15     48   28
2498     50     15     49   33
2499     50     15     50   13

In [26]:
inner_df=pd.merge(marks_df,age_df,how='inner')
display(inner_df.head())
display(inner_df.tail())

   Sno  Marks  Age
0    1     44   23
1    2     14    3
2    3     47   48
3    4     31    2
4    5     45   34

    Sno  Marks  Age
45   46     11   47
46   47     45   45
47   48     44   28
48   49     44   33
49   50     15   13

In [53]:
grouped_df=df.groupby(by='Pclass')
grouped_df.get_group(1).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S

In [56]:
#Average age in groups
print(grouped_df['Age'].mean(),
      grouped_df['Age'].min(),
      grouped_df['Age'].count(),   sep='\n\n')

Pclass
1    38.233441
2    29.877630
3    25.121243
Name: Age, dtype: float64

Pclass
1    0.92
2    0.67
3    0.42
Name: Age, dtype: float64

Pclass
1    186
2    173
3    354
Name: Age, dtype: int64